[build]
    publish="build"

[context.production.environment]
  REACT_APP_EVENTBRITE_CLIENT_ID = ""

  # The following redirect is intended for use with most SPAs that handle
  # routing internally.
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200